#! /usr/bin/env python3

# Using /home/teuben/LMT/lmtoy/data_lmt/unity/data_lmt.log
# 2018-S1-MU-57 - Science
#   script generated by source_obsnum.sh
import os
import sys

from lmtoy import runs

project="2018-S1-MU-57"

# Dictionary of sources, each with a list of obsnum's in this project
# negative obsnums are ignored in the combinations. See also comments.txt
# for obsnum specific comments and parameters!
on = {}

on["HerBS-195"] = \
 [ 76785, 76786, 76787, 76789, 76790, 76791, 77174, 77175, 77176, 77178, 77179, 77180,]

# parameters for the first pass of the pipeline (restart=1 is automatically enforced here)
pars1 = {}

pars1["HerBS-195"] = ""

# parameters for the (optional) second pass of the pipeline (e.g. for bank=0)
pars2 = {}

pars2["HerBS-195"] = ""

# parameters for the (optional) third pass of the pipeline (usually for bank=1)
pars3 = {}

pars3["HerBS-195"] = ""

# Found 1 source(s) for 2018-S1-MU-57

if __name__ == "__main__":
    runs.mk_runs(project, on, pars1, pars2, pars3, sys.argv)
